ethereum client unit tests
LimeChain/hedera-evm-bridge-validator pull request #244
Opened 2021-06-02 10:25 UTC by Holymir

Signed-off-by: Ventsislav Tsochev <ventsi@limechain.tech>

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-06-02 12:11 UTC, georgiyazovaliiski requested changes

2021-06-02 12:11 UTC, georgiyazovaliiski commented on app/clients/ethereum/client_test.go
> +}
You can initialize a "mocked" client as a global variable and use it as expectation when asserting the client returned from `NewClient` and `GetClient`

2021-06-02 12:11 UTC, georgiyazovaliiski commented on app/clients/ethereum/client_test.go
> +	assert.NotNil(t, address)
Is there any way to assert the address value?

2021-06-02 12:11 UTC, georgiyazovaliiski commented on app/clients/ethereum/client_test.go
> +}
Can we actually assert which method gets called?

2021-06-03 06:03 UTC, georgiyazovaliiski commented on app/clients/hedera/client_test.go
> +	assert.NotNil(t, client)
Here you assert that the client is not nil. Are there any properties inside the client that differ it from the other 2 tests related to getting different types of clients?

2021-06-03 10:25 UTC, georgiyazovaliiski approved these changes

2021-09-21 06:20 UTC, Daniel-K-Ivanov commented
Closing this PR since the unit tests for the clients have been implemented in #303

2021-09-21 06:20 UTC, closed without merging